name: polyhedra_lint
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
