name: polyhedra_lint
description: Shared library for common linting rules across Polyhedra projects
version: 1.0.0
repository: http://butterfree.lan:30130/dart/polyhedra-lint
publish_to: http://butterfree.lan:30117

environment:
  sdk: ^3.1.0

dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
