name: polyhedra_lint
description: Shared library for common linting rules across Polyhedra projects
version: 1.0.1
repository: https://github.com/Polyhedra-Studio/Polyhedra-Dart-Lint.git

environment:
  sdk: ^3.1.0

dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
